name: Deploy Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Assuming pytest is used for tests
        pip install pytest
        pytest

    - name: Upload package to Azure Function App
      env:
        AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        # Login to Azure using service principal
        echo "$AZURE_CREDENTIALS" > myAzureCredentials.json
        az login --service-principal -u $(jq -r '.clientId' < myAzureCredentials.json) \
                 -p $(jq -r '.clientSecret' < myAzureCredentials.json) \
                 --tenant $(jq -r '.tenantId' < myAzureCredentials.json)
        rm myAzureCredentials.json

        # Deploy with zip deployment
        func azure functionapp publish $AZURE_FUNCTIONAPP_NAME --python

    - name: Cleanup Azure login
      run: |
        az logout
